import Foundation

extension Notification.Name {
    static let renameActiveTab = Notification.Name("MuxyRenameActiveTab")
    static let toggleThemePicker = Notification.Name("MuxyToggleThemePicker")
    static let themeDidChange = Notification.Name("MuxyThemeDidChange")
    static let findInTerminal = Notification.Name("MuxyFindInTerminal")
    static let openVCSWindow = Notification.Name("MuxyOpenVCSWindow")
    static let toggleAttachedVCS = Notification.Name("MuxyToggleAttachedVCS")
    static let toggleFileTree = Notification.Name("MuxyToggleFileTree")
    static let refocusActiveTerminal = Notification.Name("MuxyRefocusActiveTerminal")
    static let quickOpen = Notification.Name("MuxyQuickOpen")
    static let commandPalette = Notification.Name("MuxyCommandPalette")
    static let switchWorktree = Notification.Name("MuxySwitchWorktree")
    static let saveActiveEditor = Notification.Name("MuxySaveActiveEditor")
    static let windowFullScreenDidChange = Notification.Name("MuxyWindowFullScreenDidChange")
    static let toggleSidebar = Notification.Name("MuxyToggleSidebar")
    static let toggleNotificationPanel = Notification.Name("MuxyToggleNotificationPanel")
    static let toggleAIUsage = Notification.Name("MuxyToggleAIUsage")
    static let toggleSnippetsPanel = Notification.Name("MuxyToggleSnippetsPanel")
    static let toggleInspectorPanel = Notification.Name("MuxyToggleInspectorPanel")
    static let toggleProjectNotesPanel = Notification.Name("MuxyToggleProjectNotesPanel")
    static let toggleProjectTodoPanel = Notification.Name("MuxyToggleProjectTodoPanel")
    static let toggleAIAssistant = Notification.Name("MuxyToggleAIAssistant")
    static let vcsRepoDidChange = Notification.Name("MuxyVCSRepoDidChange")
}
